### ISSUE TITLE
kick

### ISSUE THREAD

**Issue by L3G3CLAN** [SlimHostdev/discord_v13_main_bot#1]
```
TypeError: Cannot read properties of undefined (reading 'id')
at Object.module.exports.run (/home/container/admincommands/kick.js:17:82)
at Client.<anonymous> (/home/container/index.js:209:27)
    at Client.emit (node:events:527:28)
at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:25:14)
at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
```

**Comment by L3G3CLAN** [comment]
in the new update this is /kick
